### PR TITLE
Add exports to several request policy factory methods

### LINKED ISSUE #334: Export generateClientRequestIdPolicy, proxyPolicy, throttlingRetryPolicy, getDefaultProxySettings
**Is your feature request related to a problem? Please describe.**
Trying to use generateClientRequestIdPolicy() when customizing the request policy factories but it is not available.

**Describe the solution you'd like**
Export `generateClientRequestIdPolicy` in msRest.ts similar to other policies.

**Describe alternatives you've considered**
Copy code to implement similar functionality

### PR DESCRIPTION
**Pull request by jeremymeng**
They are useful when customizing the requestPolicyFactories array of a
ServiceClientOptions instance.

Resolves #334.

### CODE REVIEW

**Comment by kpajdzik** [comment]
LGTM. @daschult, what do you think?

**Comment by kpajdzik** [comment]
@jeremymeng, do you mind updating the version in package.json to 1.8.0? I can't push to your fork. After that it's good to go.

**Comment by jeremymeng** [comment]
Version updated. Thank all for reviewing!

**Comment by kpajdzik** [comment]
@jeremymeng I forgot about version from Constants.ts (https://github.com/Azure/ms-rest-js/blob/master/lib/util/constants.ts#L11). If you could update that as well, I'd appreciate a lot :) Sorry for missing that!

**Comment by jeremymeng** [comment]
@kpajdzik no problem!

**Comment by kpajdzik** [comment]
@jeremymeng, This should be published in the next hour. Thanks for your contribution :)

**Pull request merged**
