### PR TITLE
Es interop

### LINKED ISSUE #231: Enable esModuleInterop in tsconfig
Right now we don't have `esModuleInterop: true` in tsconfig and this allows us to sometimes produce code that's not semantically valid. This causes some tools like rollup that consume our esm outputs to fail.

e.g.

```js
import * as uuid from "uuid/v4";
uuid();
```

Let's fix these usages by enabling `esModuleInterop: true` as well as `allowSyntheticDefaultImports: true` so the usage changes to:

```js
import uuid from "uuid/v4";
uuid();
```

This is a preview blocker.
@bterlson

### PR DESCRIPTION
**Pull request by RikkiGibson**
Resolves #231 

@bterlson

### CODE REVIEW

**Comment by bterlson** [comment]
👍👍

**Comment by RikkiGibson** [comment]
Pretty mystified-- tests run great locally but I get `webpackDevMiddleware is not a function` in CI.

**Comment by RikkiGibson** [comment]
Should not have been mystified :P

**Comment by RikkiGibson** [comment]
Will want to keep an eye on usages like `import * as tough from "tough-cookie"` in case that turns out to break rollup or something.

**Pull request merged**
