### PR TITLE
build(deps): updates axios

### PR DESCRIPTION
**Pull request by juliuscc**
Axios has recently fixed a vulnerability. This upgrade makes sure that the safe version of axios is used.

### CODE REVIEW

**Comment by joheredi** [comment]
@juliuscc thanks a lot for contributing! The changes look good and the tests passed, would you mind bumping the version so that the step `Check_Everything` passes? You just need to run `npm version patch` which will bump the version and commit, and then you'll need to push the change.

**Comment by ramya-rao-a** [comment]
@joheredi I just pushed a commit for the version bump

**Comment by joheredi** [comment]
> @joheredi I just pushed a commit for the version bump

Thanks! I'll run a couple of sanity tests and will merge

**Comment by joheredi** [comment]
Sanity testing went okay, merging after PR build completes

**Comment by juliuscc** [comment]
Thanks!!! ✨

**Pull request merged**
