### PR TITLE
Match types version of uuid

### PR DESCRIPTION
**Pull request by alexrecuenco**
UUID was updated to 8.3.2, but @types/uuid was still using the 3.x version

### CODE REVIEW

**Comment by jeremymeng** [comment]
@alexrecuenco thank you very much for your contribution!  The change looks good. I am curious about your usage on `@azure/ms-rest-js`. What functionality are you using?  If you are just using the http client, I want to let you know that we have created a new package `@azure/core-rest-pipeline` and made a lot of improvements there.

**Comment by jeremymeng** [comment]
@deyaaeldeen It looks that the Test autorest.typescript build pipeline is failing likely because .NET core 2.0 is no longer available in vm image. The test is using v4x branch.  Is it possible to either add a step to install .NET Core 2.0, or upgrade to use later version of .NET.

**Review by jeremymeng — APPROVED** [review]

**Comment by jeremymeng** [comment]
Merging. The build failure is unrelated.

**Comment by alexrecuenco** [comment]
> @alexrecuenco thank you very much for your contribution!  The change looks good. I am curious about your usage on `@azure/ms-rest-js`. What functionality are you using?  If you are just using the http client, I want to let you know that we have created a new package `@azure/core-rest-pipeline` and made a lot of improvements there.

I am using it indirectly through the bot framework. I was exploring how some internals work and noticed the dependency inconsistency, so I thought it would be helpful to provide a PR for the small change

**Pull request merged**
