### PR TITLE
Wrap trusted-types policy creation in a try/catch

### PR DESCRIPTION
**Pull request by Zlatkovsky**
In our use-case of the ms-rest-js library, we have a large existing application (complete with caching, service-workers, etc) that we dynamically load additional JavaScript code into. The additional JS is what brings in the ms-rest-js.

The application has Trusted Types enabled (e.g., CSP rule `'trusted-types LibraryA LibraryB etc`). But, interestingly, its `require-trusted-types-for 'script'` is currently under "report only" (`Content-Security-Policy-Report-Only`). In those cases, a call to `trustedTypes.createPolicy` will fail because the policy isn't on the allowed-list, even though _skipping_ the `createPolicy` would be OK. So in effect, https://github.com/Azure/ms-rest-js/commit/531aea9bfbbe6ef6c06984ab06f99775b90923ca introduced a regression.

We are working on extending the allow-list of our application to include `@azure/ms-rest-js#xml.browser`, but that change takes time. In the meantime, we'd like to wrap the policy-creation in a `try/catch`. There is no security risk to it, since for host applications that DO have strict enforcement of trusted-types, the code will simply fail when the dangerous sink is used (e.g., when doing `parseFromString`). And likewise, wrapping in `try/catch` and doing nothing on `catch` is OK, because the code already deals with the possibility of the trustedTypes API not being available on the browser.

### CODE REVIEW

**Comment by jeremymeng** [comment]
> But, interestingly, its `require-trusted-types-for 'script'` is currently under "report only" (`Content-Security-Policy-Report-Only`). In those cases, a call to `trustedTypes.createPolicy` will fail because the policy isn't on the allowed-list, even though _skipping_ the `createPolicy` would be OK

If `createPolicy` is skipped, there would be issues reported for our usages of `parseFromString`?

**Comment by jeremymeng** [comment]
> If it's **off** (or report-only),

Does "report-only" mean `Content-Security-Policy-Report-Only: require-trusted-types-for 'script';`? Under this setting, `createPolicy` is bypassed, would usage of `parseFromString` be reported?

**Comment by Zlatkovsky** [comment]
> Does "report-only" mean `Content-Security-Policy-Report-Only: require-trusted-types-for 'script';`? Under this setting, `createPolicy` is bypassed, would usage of `parseFromString` be reported?

Yes. With the try/catch change proposed in the PR, the `createPolicy` would fail and thereby not create a policy. Then, if the host application has `Content-Security-Policy-Report-Only: require-trusted-types-for 'script';` (which is exactly the setup we had), the browser would see that someone is trying to call `parseFromString` without having the string having been first sanitized by a policy, and hence would flag it with a warning in the console and a report to the CSP report URL.

_Screenshot showing how it would look on the Console; only the second message is relevant for this case:_
Screenshot showing how it would look on the Console; only the second message is relevant for this case

**Comment by Zlatkovsky** [comment]
@jeremymeng , gentle ping.

**Comment by jeremymeng** [comment]
@Zlatkovsky v2.6.4 is now on npmjs.

**Pull request merged**
